[package]
name = "arise-status"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
dotenv = "0.15.0"
log = { version = "0.4.26", features = ["kv_serde"] }
reqwest = "0.12.12"
serde = "1.0.218"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
